import { StyleSheet } from "react-native";
import { COLORS } from "@/constants/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
    padding: 25,
    justifyContent: "center",
    alignItems: "center",
  },
  illustration: {
    width: 250,
    height: 250,
    resizeMode: "contain",
    borderRadius: 15,
    marginBottom: 20,
  },
  title: {
    fontSize: 34,
    fontWeight: "700",
    color: COLORS.text,
    marginBottom: 25,
    textAlign: "center",
    fontFamily: "Helvetica",
  },
  input: {
    backgroundColor: COLORS.white,
    borderRadius: 15,
    padding: 18,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
    fontSize: 17,
    color: COLORS.text,
    width: "85%",
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 5,
  },
  errorInput: {
    borderColor: COLORS.expense,
    borderWidth: 2,
  },
  button: {
    backgroundColor: COLORS.primary,
    borderRadius: 15,
    paddingVertical: 15,
    paddingHorizontal: 30,
    alignItems: "center",
    marginVertical: 20,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  buttonText: {
    color: COLORS.white,
    fontSize: 20,
    fontWeight: "600",
    letterSpacing: 0.5,
  },
  footerContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 5,
  },
  footerText: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: "500",
  },
  linkText: {
    color: COLORS.primary,
    fontSize: 16,
    fontWeight: "600",
    textDecorationLine: "underline",
  },
  errorBox: {
    backgroundColor: "#FFF3F3",
    padding: 12,
    borderRadius: 10,
    borderLeftWidth: 5,
    borderLeftColor: COLORS.expense,
    marginBottom: 20,
    flexDirection: "row",
    alignItems: "center",
    width: "85%",
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 4,
  },
  errorText: {
    color: COLORS.text,
    marginLeft: 10,
    flex: 1,
    fontSize: 15,
    fontWeight: "500",
  },
});